### ISSUE TITLE
Auswahl eines C++ Loggers

### ISSUE THREAD

**Issue by authaldo** [SoPra-Team-17/Server#1]
Da die C++ Standardbibliothek leider keine Logger bereitstellt, sollten wir uns nach einem anderen Logging-Framework umschauen (oder selber eins schreiben). 

Anforderungen wären aus meiner Sicht:

- nutzbar mit mehreren Threads
- Logging zu mehreren Senken (z.B. Konsole und Logfile)
- farblich hervorgehobenes Logging für die Konsole
- Log-Level: info, warning, error, critical

Welche Anforderungen seht ihr sonst noch?

Um direkt auch mal noch ein paar Vorschläge in den Raum zu werfen: 

- [spdlog](https://github.com/gabime/spdlog)
- [Easylogging++](https://github.com/amrayn/easyloggingpp)

Ich hab bisher mit keinem der beiden gearbeitet, allerdings gefällt mir bei Easylogging++ die Nutzung des << operators.

Hat von euch da schon jemanden Erfahrungen?

**Comment by ottojo** [comment]
Ich habe gerade mal spdlog installiert und ausprobiert, war soweit schmerzlos, integration mittels systemweit installierter lib und cmake funktioniert.

**Comment by ottojo** [comment]
Also ich wollte gerade Easylogging++ ausprobieren und hab schon keinen Spaß mehr... Cmake wird nicht unterstützt, Installation="kopier die files da hin oder so", Makro-fuckery, hierarchische loglevel sind nonstandard und absolut fucked (wtf warum ist Warning zwischen Info und Debug??? https://github.com/amrayn/easyloggingpp#level), die haben sich irgendwie ein eigenes config-file-format überlegt? (https://github.com/amrayn/easyloggingpp#using-configuration-file)

**Comment by authaldo** [comment]
Wenn es bei spdlog nichts auszusetzen gibt, können wir doch auch einfach das nehmen. Das mit dem << Operator wäre aus meiner Sicht nur das i-Tüpfelchen gewesen, weil man die Formatierung der Ausgabe dann direkt dort hätte vornehmen können. 
Aber spdlog + stringstream wenn man denn wirklich was speziell formatieren möchte geht von meiner Seite aus auch vollkommen in Ordnung. 

Gibts noch andere Einwände zu den Loggern? Sonst könnte man sich da festlegen

**Comment by ottojo** [comment]
da es bisher keine weiteren kommentare gibt, verwenden wir spdlog
