### ISSUE TITLE
Fehlende MetaInformationen

### ISSUE THREAD

**Issue by Marco5de** [SoPra-Team-17/Server#101]
Ich requeste beim Spectator Client die UUID von `MetaInformationKey::FACTION_PLAYER1`, `MetaInformationKey::FACTION_PLAYER2`,  `MetaInformationKey::FACTION_NEUTRAL`.
Allerdings werden vom Server nur die UUID für die Neutrals (npc) gesendet.
Siehe log im Anhang, relevant ist die zuletzt gesendete MetaInformation message.

[out.log](https://github.com/SoPra-Team-17/Server/files/4736308/out.log)

**Comment by authaldo** [comment]
Wenn ich das beim Überfliegen richtig sehe, dann hast du das als Spectator requested, oder? 
Aktuell sind da noch TODOs im Code, dass wir die Infos auch an Zuschauer rausgeben.

**Comment by Marco5de** [comment]
Genau. Ich hab das als Spectator requested und erhalte das für Player1 und Player2 eben nicht, sondern nur die Neutrals
