### ISSUE TITLE
Kick players

### ISSUE THREAD

**Issue by authaldo** [SoPra-Team-17/Server#113]
Im Falle eines Kicks muss die Victory Reason entsprechend als VICTORY_BY_KICK gesetzt werden.

**Comment by ottojo** [comment]
TODO:
* [ ] Errormessage senden
* [ ] Connection trennen
* [ ] Spiel beenden, gewinn mit `VICTORY_BY_KICK` über `action::closeGame`

**Comment by authaldo** [comment]
Notwendig bei folgenden Aktionen:
 - [x] falscher Auswahl in der ItemChoice
 - [x] falsche Auswahl in der EquipmentChoice
 - [ ]  nicht erlaubte Nachricht der KI
