### ISSUE TITLE
Auswahl eines C++ Argument Parsers

### ISSUE THREAD

**Issue by authaldo** [SoPra-Team-17/Server#2]
Wir sollten uns mal nach einem Argument Parser für das Command Line Interface umsehen. 
Der Standard schreibt folgendes vor:
* `-c <path>` / `--config-charset <path>`
* `-m <path>` / `--config-match <path>`
* `-s <path>` / `--config-scenario <path>`  
* `-h` / `--help` (optional)
* `-v <int>` / `--verbosity <int>` (optional)
* `-p <int>` / `--port <int>`  (optional)
* `--x <key> <value>`

Besonders interessant könnte dabei die letzte Zeile werden, da sich dieses Flag auf die zwei nachfolgenden (getrennten) Parameter bezieht, und nicht wie gewöhnlich auf eins. 
Damit entfällt [getoptlong](https://linux.die.net/man/3/getopt_long) als Option, da es gemäß dieses Users [hier](https://stackoverflow.com/questions/8559391/supplying-two-arguments-to-command-line-option-using-getopt) nicht damit klar kommt. Hinzu kommt, dass getoptlong aus der C-Ecke kommt.
Auch [gflags](https://gflags.github.io/gflags/) hat gemäß der Beschreibung dasselbe Problem.
Eine weitere Möglichkeit wäre [cxxopts](https://github.com/jarro2783/cxxopts), allerdings scheint die Problematik hier diesselbe zu sein. 

Hat von euch da eventuell jemand schon Erfahrungen in dem Bereich? 
Ansonsten müsste man sich da eventuell auch selber was basteln oder lässt der Standard zu, dass man das Key-Value-Pair in Anführungszeichen packt?

**Comment by ottojo** [comment]
> --x: Ermöglicht es optionale Schlüssel-Wert-Paare zu übermitteln, die verfügbaren Einstellungen sind proprietär.
Hört sich für mich so an als ob das eher so wildcard-mäßig für eigene argumente gedacht ist, oder?
Wenn ja, kann man sich da für doch viel eleganter eigene optionen definieren, oder?

**Comment by ottojo** [comment]
habe ein bisschen mit cxxopts und argparse und args experimentiert, finde args(https://github.com/Taywee/args) momentan am coolsten

**Comment by ottojo** [comment]
Ich schau das später noch mal im Detail an, aber https://github.com/CLIUtils/CLI11 gefällt mir spontan sehr gut, erinnert mich an das Go "flag" package (Variablen für Optionen, parse() füllt diese per referenz darauf)

**Comment by authaldo** [comment]
Ich bin von CLI11 vollkommen überzeugt und habe dazu mal ein kleines [Testprogramm](https://github.com/SoPra-Team-17/Server/pull/3) geschrieben.

**Comment by ottojo** [comment]
Ich würde mal sagen wir verwenden CLI11
