### ISSUE TITLE
Lib für StateMachine suchen

### ISSUE THREAD

**Issue by ottojo** [SoPra-Team-17/Server#30]
Deadline: Heute Abend

**Comment by ottojo** [comment]
* [tinyfsm](https://github.com/digint/tinyfsm)
  * Keine transition-table
  * Sehr minimal, wenig overhead
  * Keine speziellen Konstrukte für Hierarchie

**Comment by ottojo** [comment]
* [afsm](https://github.com/zmij/afsm)
  * minimalbeispiel kompiliert nicht, cmake kaputt oder so

**Comment by authaldo** [comment]
Was afsm angeht fehlt im cmake lediglich der include der include directories, wobei noch zu erwähnen ist, dass neben afsm auch [metapushkin](https://github.com/zmij/metapushkin) benötigt und includiert werden muss.

**Comment by authaldo** [comment]
Wir haben uns entschlossen es mit afsm zu versuchen, vorwiegend wegen der Möglichkeit der states im state.
