### ISSUE TITLE
Behandlung der Retire Action

### ISSUE THREAD

**Issue by Marco5de** [SoPra-Team-17/Server#79]
> [2020-05-28 15:23:22.500] [Logger] [info] Initialized round order:
> [2020-05-28 15:23:22.500] [Logger] [info] Holly Norton 	(e2e6a74b-c0aa-41a9-bd1c-96ef17fd2524)
> [2020-05-28 15:23:22.500] [Logger] [info] Zoe Nonnenmache 	(f21cda33-48f5-4c92-99a9-cc30bc762b03)
> [2020-05-28 15:23:22.500] [Logger] [info] Lewis Holl 	(fd3dd1ea-5b27-4190-9b49-8d59639d8aa0)
> [2020-05-28 15:23:22.500] [Logger] [info] Holly Harrington 	(c559802e-c337-4e08-b518-56b4876ca106)
> [2020-05-28 15:23:22.500] [Logger] [info] Arran Fassbender 	(4f73f105-11bd-4ca5-9e4c-1b78b282c025)
> [2020-05-28 15:23:22.500] [Logger] [info] James Bond 	(5ecb0574-6020-467f-94a0-2f485f670b72)
> [2020-05-28 15:23:22.500] [Logger] [info] Aria Jones 	(a9fd0986-d7fa-4a01-8c20-717d8d623706)
> [2020-05-28 15:23:22.500] [Logger] [info] Charlotte Taylor 	(164f3c71-3480-4698-8a01-ad9bc9b05752)
> [2020-05-28 15:23:22.500] [Logger] [info] Claire Norton 	(1b8edeab-a107-47e2-8ab0-01a316dfbeb0)
> [2020-05-28 15:23:22.500] [Logger] [info] Rosie Hoelle 	(24b65bce-b0b3-4034-bcab-a1b486aa6810)
> [2020-05-28 15:23:22.500] [Logger] [info] Karen Dayton 	(ecb73e7a-7735-484c-9de3-f7d6d9d6d858)
> [2020-05-28 15:23:22.500] [Logger] [info] Terry Wood 	(54ded027-9472-400b-bc9d-1d4eacded00e)
> [2020-05-28 15:23:22.500] [Logger] [info] Broadcasting state
> [2020-05-28 15:23:22.507] [Logger] [info] Requesting Operation for character Holly Norton from player two
> [2020-05-28 15:23:22.507] [Logger] [info] Entering state waitingForOperation
> [2020-05-28 15:23:31.512] [Logger] [info] Handling some operation
> [2020-05-28 15:23:31.512] [Logger] [info] Executing "RETIRE" action
> [2020-05-28 15:23:31.512] [Logger] [info] Broadcasting state
> [2020-05-28 15:23:31.518] [Logger] [info] Requesting Operation for character Holly Norton from player two

Obige Log Output darf eigentich nicht Zustande kommen. es wird eine Action von Holly Requested. Es wird eine Retire Action empfangen und ansachließend wieder eine Action von Holly requested.

**Comment by ottojo** [comment]
Retire setzt AP und MP auf 0, das sollte also mit #78 auch gefixt werden. Interessant aber, dass überhaupt eine zweite action requested wird...
