### ISSUE TITLE
Segfault bei Gadget Aktion

### ISSUE THREAD

**Issue by Marco5de** [SoPra-Team-17/Server#81]
> [2020-05-29 11:11:27.788] [Logger] [info] Broadcasting state
> [2020-05-29 11:11:27.794] [Logger] [info] Generating NPC action
> [2020-05-29 11:11:27.794] [Logger] [info] Executing "GADGET_ACTION" action
> Segmentation fault (core dumped)

Ist jetzt bereits mehrfach aufgetreten, dass eine NPC Aktion generiert werden soll und dann eine Gadget Aktion ausgeführt wird und es zu einem Segmenation Fault kommt.

**Comment by ottojo** [comment]
Konnte ich bisher nicht reproduzieren, habe aber momentan auch nur den testClient vom server zur verfügung. Wie kann das reproduziert werden?

**Comment by Marco5de** [comment]
Soweit ich das sehe, passiert es ab und zu beim Ausführen einer Gadget Aktion die für einen NPC erstellt wurde. Ich schätze mal, dass es für ein bestimmtes Gadget fehl schlägt. 
Es segfaulted auch nicht jedes mal.

**Comment by ottojo** [comment]
Ok, ich teste mal noch ein bisschen mehr um das vielleicht einzugrenzen.

**Comment by Marco5de** [comment]
Ich hab das ganze jetzt auch bei einer Spieleraktion bekommen. Habe folgende Aktion ausgeführt

Gadget Aktion, Cocktail, auf Nachbarfeld auf welchem ein Cocktail steht.
Also aufnehmen des Cocktails ins Inventar.

**Comment by ottojo** [comment]
Trat bei mir auch gerade auf bei moledie action eines NPCs

**Comment by ottojo** [comment]
wohl related zum hinzufügen eines gadgets zu einem character
