### ISSUE TITLE
Vom Janitor rausgeschmissene Character sind in der Zugreihenfolge 

### ISSUE THREAD

**Issue by ottojo** [SoPra-Team-17/Server#99]
(sollte nicht so sein, oder? bewirkt dann nämlich z.B. https://github.com/SoPra-Team-17/LibCommon/issues/298 )

**Comment by Marco5de** [comment]
Ist noch aktuell und im Client ein Problem.
Server fordert Aktion vom Client an, obwohl dieser keinen Charakter mehr auf dem Spielfeld hat.
